#! /bin/bash

set -e

print_help()
{
    cat >&2 <<MSG
apt-get-from-librarian: Install packages from launchpad librarian
=================================================================

This tool can install old version of ubuntu packages from launchpad librarian.

Usage:

    # apt-get-from-librarian [<PACKAGE1=VERSION1>...]

Options:

-h, --help                  Show this message.
-a, --arch ARCH             Set arch (default $opt_arch)
-d, --distro DISTRO         Set ubuntu distro codename (default $opt_distro)

Example:

    # apt-get-from-librarian gcc-9=9.3.0-17ubuntu1~20.04 g++-9=9.3.0-17ubuntu1~20.04

It is implemented as a standalone single-file bash script.

Homepage: https://gitlab.com/cdleonard/apt-get-from-librarian
MSG
}

get_librarian_link()
{
    sed -ne 's/.*href="\(http:\/\/launchpadlibrarian.*\)".*/\1/p'
}

exit_trap()
{
    rm -rf "$tmpdir"
}

parse_args()
{
    # Defaults
    opt_arch=amd64
    opt_distro=focal
    opt_pkg_list=()

    if [[ $OSTYPE = darwin* ]]; then
        if [[ -x /usr/local/opt/gnu-getopt/bin/getopt ]]; then
            getopt() { /usr/local/opt/gnu-getopt/bin/getopt "$@"; }
        else
            echo >&2 "Need gnu getopt"
            exit 2
        fi
    fi

    # Scan args
    local LONG_OPTS="help,arch:,distro:"
    local opts
    opts=$(getopt -n "$0" -l "$LONG_OPTS" -o +ha:d: -- "$@")
    eval set -- "$opts"
    while [ $# -gt 0 ]; do
        case "$1" in
        -h|--help) print_help; exit 1 ;;
        -a|--arch) opt_arch=$2; shift ;;
        -d|--distro) opt_distro=$2; shift ;;
        --)
            shift
            opt_pkg_list=("$@")
            break
            ;;
        *)
            echo >&2 "unrecognized argument $1"
            exit 2
            ;;
        esac
        shift
    done
}


main()
{
    local pkg_arg
    local link
    local link_list=()
    local dpkg_list=()

    parse_args "$@"

    tmpdir=$(mktemp -d)
    trap exit_trap EXIT

    for pkg_arg in "${opt_pkg_list[@]}"; do
        local pn pv
        if [[ $pkg_arg != *=* ]]; then
            echo "Bad package argument $pkg_arg needs to be of the form PKG=VER"
        fi
        pn=${pkg_arg%%=*}
        pv=${pkg_arg#*=}
        link=$(curl -s "https://launchpad.net/ubuntu/$opt_distro/$opt_arch/$pn/$pv" | get_librarian_link)
        if [[ -z $link ]]; then
            echo "FAIL on $pn=$pv"
            exit 1
        fi
        link_list+=("$link")
    done
    (
        cd "$tmpdir"
        curl_cmd=(curl -Z)
        for link in "${link_list[@]}"; do
            curl_cmd+=(-O "$link")
            dpkg_list+=(./"$(basename "$link")")
        done
        "${curl_cmd[@]}"
        apt-get install -y --no-install-recommends "${dpkg_list[@]}"
    )
}

main "$@"
